#+BEGIN_COMMENT
.. title: Walking Through the PyViz Network Graphs Examples
.. slug: walking-through-the-pyviz-network-graphs-examples
.. date: 2019-03-20 14:55:24 UTC-07:00
.. tags: tutorial,pyviz
.. category: Tutorial
.. link: 
.. description: Walking through the pyviz network graphs examples.
.. type: text
.. status:
.. updated: 

#+END_COMMENT
#+OPTIONS: ^:{}
#+TOC: headlines 2
#+BEGIN_SRC python :session giss :results none :exports none
%load_ext autoreload
%autoreload 2
#+END_SRC
* Beginning
  This is a walk-through of the [[http://pyviz.org/tutorial/06_Network_Graphs.html][pyviz networks graphs examples]] so I can check that I can replicate them.
** Imports
*** Python
#+begin_src python :session pyviz :results none
from pathlib import Path
from functools import partial
import os
#+end_src
*** PyPi
#+begin_src python :session pyviz :results none
from bokeh.models import HoverTool
from dotenv import load_dotenv
from holoviews import opts, dim
from holoviews.operation.datashader import bundle_graph

import holoviews
import networkx
import numpy
import pandas
#+end_src
*** My Stuff
#+begin_src python :session pyviz :results none
from graeae.visualization import EmbedBokeh
from graeae.tables import CountPercentage
#+end_src
** Setup
*** The Plotting
#+begin_src python :session pyviz :results none
class Plot:
    width = 800
    height = 800
    padding = 0.1
    fontsize = 24
holoviews.extension("bokeh")
defaults = dict(width=Plot.width, height=Plot.height, padding=Plot.padding, xaxis=None, yaxis=None,
                fontsize=Plot.fontsize)
holoviews.opts.defaults(
    opts.EdgePaths(**defaults),
    opts.Graph(**defaults),
    opts.Nodes(**defaults),
)
#+end_src
*** The Bokeh Embedder
#+begin_src python :session pyviz :results none
OUTPUT_FOLDER = Path("../../files/posts/libraries/"
                     "walking-through-the-pyviz-network-graphs-examples/")
Embed = partial(EmbedBokeh, folder_path=OUTPUT_FOLDER)
#+end_src
* Middle
** A Simple Graph
   You can define a graph by giving two arrays which together represent pairs of nodes connected by an edge (they call the first array the nodes and the second the edges). As an example we can create a graph where all the nodes (other than the first node) have an edge to the first node (Node 0 in this case).

#+begin_src python :session pyviz :results output raw :exports both
NODE_COUNT = 10
NODES = numpy.arange(NODE_COUNT)
EDGES = numpy.ones(NODE_COUNT) * 5

graph = holoviews.Graph(((EDGES, NODES),)).opts(title="We're All Connected to Five")
Embed(graph, "first_graph")()
#+end_src

#+RESULTS:
#+begin_export html
<script src="first_graph.js" id="2b9cdb9c-fb7d-4852-afb8-ff2d79cddff1"></script>
#+end_export

The arguments to the =Graph= looks odd, and it's not obvious from the docstring why you need to pass in a tuple of tuples, but you do.

If you hover over the nodes you'll see that they all connect to the one with =index= 5, the value we gave to the edges array.
** Re-Using the Nodes and Edges
   The =Graph= keeps the =Nodes= and =EdgePaths= as separate objects that are themselves plotable.

#+begin_src python :session pyviz :results output raw :exports both
dimensions = dict(width=400, height=400)
plot = (graph.nodes + graph.edgepaths).opts(title="Nodes and Edges", 
                                            fontsize=Plot.fontsize, 
                                            width=400, height=400)
Embed(plot, "nodes_and_edges")()
#+end_src

#+RESULTS:
#+begin_export html
<script src="nodes_and_edges.js" id="08fa283a-f8ba-4f2f-83be-5ca28defc8a6"></script>
#+end_export

Note that changing the title worked (although it lost the font-size unless I explicitly passed it in) but changing the plot size didn't, even when I tried the =redim= method instead. This might be another one of those problematic HoloViews things that I need to figure out.
** Explicit Paths
   The next example is supposedly about suppyling explicit paths instead of letting HoloViews create them but there's so much unexplained that I'm not going to bother trying to understand it for now.

#+begin_src python :session pyviz :results output raw :exports both
def bezier(start, end, control, steps=numpy.linspace(0, 1, 100)):
    return ((1 - steps)**2 * start 
            + 2 * (1 - steps) * steps * control 
            + steps**2 * end)

x, y = graph.nodes.array([0, 1]).T

paths = []
for node_index in NODES:
    ex, ey = x[node_index], y[node_index]
    paths.append(numpy.column_stack([bezier(x[0], ex, 0), bezier(y[0], ey, 0)]))
    
padding = dict(x=(-1.2, 1.2), y=(-1.2, 1.2))
bezier_graph = holoviews.Graph(((EDGES, NODES), (x, y, NODES), paths)).redim.range(**padding)
Embed(bezier_graph, "bezier_graph")()
#+end_src

#+RESULTS:
#+begin_export html
<script src="bezier_graph.js" id="39076e44-df29-4c9c-b694-a6f0e35ba0f3"></script>
#+end_export

** Hover
   By default the hover tool will give you information about the Node you mouse-over, but you can set it to give you the nodes connected to an edge instead.

#+begin_src python :session pyviz :results output raw :exports both
graph = graph.options(inspection_policy="edges", 
                      width=Plot.width, 
                      height=Plot.height, 
                      title="Edge Hover")
Embed(graph, "edge_hove_tool")()
#+end_src

#+RESULTS:
#+begin_export html
<script src="edge_hove_tool.js" id="a991c8b1-f3bc-44bc-9c44-6978668c0c12"></script>
#+end_export

There were several things to note here:
 - Although I wasn't able to change the size when I plotted the nodes and edges side by side, this plot came out at the small size I had tried to use until I set it myself
 - The hover is now triggered by hovering over the edges
 - Although this is an undirected graph, they define the nodes as 'start' and 'end'


You can change the colors for hover activation as well.

#+begin_src python :session pyviz :results output raw :exports both
graph = graph.options(node_hover_fill_color="red",
                      edge_hover_line_color="pink")
Embed(graph, "colored_hover")()
#+end_src

#+RESULTS:
#+begin_export html
<script src="colored_hover.js" id="1898ed6f-c4f6-4e5d-ba9f-6c9bf31cb3e9"></script>
#+end_export

** More Information
   If we create the =Nodes= ourselves we can add labels to them.

First get the values that the =Graph= created for the /x/ and /y/ coordinates of the nodes.

#+begin_src python :session pyviz :results none
X, Y = graph.nodes.array([0, 1]).T
#+end_src

There's no explanation for the method that I could find, other than the docstring, so I'll just take that on faith. I don't know how you would get the values yourself without first creating a =Graph= then taking the values and creating a new one, which doesn't seem right.

Now create the labels in the same order as the nodes that they are labeling.
#+begin_src python :session pyviz :results none
node_labels = ["Barbara"] * 5 + ["Gloria"] + ["Barbara"] * 4
#+end_src

Now create the nodes and the new graph. Note that the first argument is a tuple and the nodes gets passed in as that mystery argument that I was wondering about earlier.

#+begin_src python :session pyviz :results output raw :exports both
hover = HoverTool(
    tooltips=[
        ("Name", "@Name")
    ]
)
nodes = holoviews.Nodes((X, Y, NODES, node_labels), vdims="Name")
graph = holoviews.Graph(((EDGES, NODES), nodes)).opts( 
    title="Labeled Nodes", 
    node_color="Name",
    tools=[hover],
    cmap="Set1")
Embed(graph, "named_nodes")()
#+end_src

#+RESULTS:
#+begin_export html
<script src="named_nodes.js" id="b08b52fb-88c9-453e-950f-c71b2f1f6cd4"></script>
#+end_export

** Edge Weights and Colors
   We can also change the thickness and color of the edges based on their weights. First we need to create the edge-weights.

#+begin_src python :session pyviz :results none
edge_weights = numpy.random.rand(len(EDGES))
#+end_src

=numpy.random.rand= creates an array of numbers ranging from 0 to 1 (but not 1).

Once again we have to create a new graph, this time passing in the edge-weights (and I'll add the nodes too).

#+begin_src python :session pyviz :results output raw :exports both
graph = holoviews.Graph(((EDGES, NODES, edge_weights), nodes), vdims="Weight").opts(
    opts.Graph(
    title="Edge Weights",
    inspection_policy="edges",
    node_color="Name",
    cmap="Set1",
    edge_color="Weight", 
    edge_cmap="viridis", 
    edge_line_width=holoviews.dim("Weight") * 10
        )
)
Embed(graph, "edge_weights")()
#+end_src

#+RESULTS:
#+begin_export html
<script src="edge_weights.js" id="977d191b-89fc-4eef-90db-4aee89b36b89"></script>
#+end_export

Note that the edge-hover doesn't use our node-labels, which is sort of disappointing. I wonder if there's a way to fix that.

** Using A Dataset
   I previously created the Nodes using the values from a Graph that had the Nodes, which seemed kind of circular, it turns out that the way to do it is to pass in a =Dataset= with the labels.

#+begin_src python :session pyviz :results output raw :exports both
node_labels = ("Anne Barbara Carol Donna Eleanor "
               "Francis Gloria Helen Iris Janet").split()
node_stuff = holoviews.Dataset(node_labels, vdims="Name")
graph = holoviews.Graph(
    (
        (EDGES, NODES, edge_weights), 
        node_stuff), 
    vdims="Weight").opts(
    opts.Graph(
        title="Nodes From a Dataset",
        node_color="Name",
        cmap="Set1",
        edge_color="Weight", 
        edge_cmap="plasma",
        edge_line_width=holoviews.dim("Weight") * 10,
        tools=[hover],
    )
)

Embed(graph, "dataset_node_labels")()
#+end_src

#+RESULTS:
#+begin_export html
<script src="dataset_node_labels.js" id="5aba0f29-e1a4-4420-938a-770a2c068059"></script>
#+end_export

** Using NetworkX
*** Karate Club
   First we'll load in the included karate club graph that comes with networkx. This was a graph created from the members of a karate club that eventually splintered in two. The nodes are members and an edge between two nodes meant that they socialized outside of the club.
#+begin_src python :session pyviz :results none
karate_graph = networkx.karate_club_graph()
#+end_src

This isn't explained in the example, but each node in the graph is a dict that has a some information set on it that you can reference.

#+begin_src python :session pyviz :results output :exports both
print(karate_graph.node[0])
#+end_src

#+RESULTS:
: {'club': 'Mr. Hi'}

We're going to re-use these options again so I'll store them in a variable.

#+begin_src python :session pyviz :results none
karate_options = opts.Graph(title="NetworkX Karate Club",
                            node_color=holoviews.dim("club"), cmap="Set1", 
                            xlabel="", ylabel="")
#+end_src
Now we can create the HoloViews graph from the karate club graph.
#+begin_src python :session pyviz :results output raw :exports both
graph = holoviews.Graph.from_networkx(karate_graph, 
                                      networkx.layout.circular_layout).opts(
                                          karate_options,
                                      )

Embed(graph, "karate_club")()
#+end_src

#+RESULTS:
#+begin_export html
<script src="karate_club.js" id="e5a4d0ac-cd15-41f4-b284-b3af3a0f467c"></script>
#+end_export

*** Animating the Layout
#+begin_src ipython :session pyviz :results output raw :exports both
numpy.random.seed(0)

def get_graph(iteration: int) -> holoviews.Graph:
    """Creates a graph laid out using Fruchterman-Reingold force-direction

    Args:
     iteration: maximum number of iterations to run the algorithm
    """
    return holoviews.Graph.from_networkx(karate_graph,
                                         networkx.spring_layout, 
                                         iterations=iteration)

holo_map = holoviews.HoloMap({iteration: get_graph(iteration).opts(karate_options)
                              for iteration in range(0, 55, 5)},
                             kdims="Iterations")


filename = "animated_spring.html"
path = OUTPUT_FOLDER.joinpath(filename)
holoviews.save(holo_map, path)

print('''#+begin_export html
<object type="text/html" data="{}" style="width:100%" height={}>
  <p>Failed to load</p>
</object>
#+end_export'''.format(filename, Plot.height
))
#+end_src

#+RESULTS:
#+begin_export html
<object type="text/html" data="animated_spring.html" style="width:100%" height=800>
  <p>Failed to load</p>
</object>
#+end_export

This is the first time I managed to get the holoviews widgets to work inside a post - I'm going to need to update how I do this.

** Facebook
   In this section we'll work with a graph of Facebook users who have been associated with a 'circle' (of friends).

Turn off the x and y axes.

#+begin_src python :session pyviz :results none
options = dict(width=800, height=800, xaxis=None, yaxis=None)
opts.defaults(opts.Nodes(**options), opts.Graph(**options))
#+end_src

Read in the dataframes for the edges and nodes.

#+begin_src python :session pyviz :results output
load_dotenv(".env")
edge_path = Path(os.environ.get("FACEBOOK_EDGES")).expanduser()
node_path = Path(os.environ.get("FACEBOOK_NODES")).expanduser()

assert edge_path.is_file()
assert node_path.is_file()

edge_data = pandas.read_csv(edge_path)
node_data = pandas.read_csv(node_path)

print(edge_data.shape)
print(node_data.shape)
print(node_data.iloc[0])
#+end_src

#+RESULTS:
: (2519, 2)
: (333, 4)
: x         0.346231
: y         0.294644
: index            1
: circle    circle15
: Name: 0, dtype: object

So you can see that the =circle= is part of the node data.

#+begin_src python :session pyviz :results output raw :exports both
circle_counts = CountPercentage(node_data.circle)
circle_counts()
#+end_src

#+RESULTS:
| Value    | Count | Percentage |
|----------+-------+------------|
| circle15 |   119 |      35.74 |
| None     |    56 |      16.82 |
| circle16 |    31 |       9.31 |
| circle11 |    29 |       8.71 |
| circle0  |    15 |       4.50 |
| circle19 |    13 |       3.90 |
| circle4  |    10 |       3.00 |
| circle2  |     9 |       2.70 |
| circle6  |     8 |       2.40 |
| circle17 |     8 |       2.40 |
| circle9  |     7 |       2.10 |
| circle20 |     6 |       1.80 |
| circle13 |     5 |       1.50 |
| circle10 |     4 |       1.20 |
| circle23 |     3 |       0.90 |
| circle3  |     3 |       0.90 |
| circle14 |     2 |       0.60 |
| circle7  |     2 |       0.60 |
| circle12 |     1 |       0.30 |
| circle18 |     1 |       0.30 |
| circle22 |     1 |       0.30 |

For some reason the second most circle value is =None=.

Set up the colors.

#+begin_src python :session pyviz :results none
black = "#000000"
colors = [black] + holoviews.Cycle("Category20").values
#+end_src

Setup the nodes and the graph.

#+begin_src python :session pyviz :results output raw :exports both
nodes = holoviews.Nodes(node_data).sort()
graph = holoviews.Graph((edge_data, nodes), label="Facebook Circles").opts(
    cmap=colors,
    node_size=10,
    edge_line_width=1,
    node_line_color="gray",
    node_color="circle",
)

Embed(graph, "facebook_circles")()
#+end_src

#+RESULTS:
#+begin_export html
<script src="facebook_circles.js" id="64f0f3fe-e901-4b28-909d-7724e34abb56"></script>
#+end_export

It's interesting that the most populus circle =circle15= is the first circle after we sort, is the sort working by value counts? I tried setting the second color to red, but this got assigned to =circle0= which isn't the second most common, so apparently not, but then why did it work for =circle15=?
*** Bundling
#+begin_src python :session pyviz :results output raw :exports both
bundled = bundle_graph(graph).opts(title="Bundled Facebook Circles")
Embed(bundled, "bundled_graph")()
#+end_src

#+RESULTS:
#+begin_export html
<script src="bundled_graph.js" id="44aab32c-2fc0-405c-8cda-b37c4b4f2476"></script>
#+end_export

This view helps to eliminate some of the noise from the edges, but I wonder if it does that at the expense of disproportionately diminishing the presence of =circle15= (the black circles).

*** Circles
    We can select circles from the graph instead of showing all of them.
#+begin_src python :session pyviz :results output raw :exports both
circles = circle_counts.table.Value.iloc[:5]
circle_plots = [bundled.select(circle=name, selection_mode="nodes") for name in circles]
plot = circle_plots[0]
for next_plot in circle_plots[1:]:
    plot *= next_plot
plot = plot.opts(title="Top Five Bundled Circles")
Embed(plot, "bundled_graph_circles")()
#+end_src

#+RESULTS:
#+begin_export html
<script src="bundled_graph_circles.js" id="cfea487b-0daf-4d4e-b8d1-6d49c0838bd4"></script>
#+end_export

This view helps to eliminate some of the noise from the edges, but I wonder if it does that at the expense of disproportionately diminishing the presence of =circle15= (the black circles).
