#+BEGIN_COMMENT
.. title: Walking Through the Pyviz Workflow Example
.. slug: walking-through-the-pyviz-workflow-example
.. date: 2019-03-14 12:48:04 UTC-07:00
.. tags: tutorial,pyviz
.. category: 
.. link: 
.. description: Copying the PyViz Workflow example.
.. type: text

#+END_COMMENT
#+OPTIONS: ^:{}
#+TOC: headlines 2
#+BEGIN_SRC ipython :session pyviz :results none :exports none
%load_ext autoreload
%autoreload 2
#+END_SRC
* Beginning
  This is a replication of (most of) the [[http://pyviz.org/tutorial/01_Workflow_Introduction.html][pyviz workflow introduction]] to see if I can replicate it. Nothing new here.
** Set Up
*** Imports
   From Python.
#+BEGIN_SRC ipython :session pyviz :results none
from functools import partial
from pathlib import Path
import os
#+END_SRC
From PyPi.
#+BEGIN_SRC ipython :session pyviz :results none
from bokeh.models import HoverTool
from dotenv import load_dotenv
from tabulate import tabulate

import holoviews
import hvplot.pandas
import numpy
import pandas
#+END_SRC
 My Stuff.
#+BEGIN_SRC ipython :session pyviz :results none
from graeae.visualization import EmbedBokeh
#+END_SRC
*** Presets
    Load the dotenv.
#+BEGIN_SRC ipython :session pyviz :results none
load_dotenv(".env")
#+END_SRC

Set up the bokeh.
#+BEGIN_SRC ipython :session pyviz :results none
OUTPUT_FOLDER = Path("../../files/posts/libraries/walking-through-the-pyviz-workflow-example/")
Embed = partial(EmbedBokeh, folder_path=OUTPUT_FOLDER)
holoviews.extension("bokeh", width=800)
#+END_SRC

Set up the table printer.
#+BEGIN_SRC ipython :session pyviz :results none
TABLE = partial(tabulate, tablefmt="orgtbl", headers="keys", showindex=False)
#+END_SRC

*** Load Some Data
    Measles and pertusis by state.
#+BEGIN_SRC ipython :session pyviz :results none
diseases = pandas.read_csv(Path(os.environ.get("DISEASES")))
#+END_SRC

#+BEGIN_SRC ipython :session pyviz :results output raw :exports both
print(TABLE(diseases.head()))
#+END_SRC

#+RESULTS:
| Year | Week | State   | measles | pertussis |
|------+------+---------+---------+-----------|
| 1928 |    1 | Alabama |    3.67 |       nan |
| 1928 |    2 | Alabama |    6.25 |       nan |
| 1928 |    3 | Alabama |    7.95 |       nan |
| 1928 |    4 | Alabama |   12.58 |       nan |
| 1928 |    5 | Alabama |    8.03 |       nan |

* Middle
** Looking at Measles
*** By Year
#+BEGIN_SRC ipython :session pyviz :results output raw :exports both
hover = HoverTool(
    tooltips=[
        ("Measles", "@measles{0,0}"),
        ("Year", "@Year"),
    ],
    formatters={"measles": "numeral"},
    mode="vline",
)

measles_by_year = diseases[["Year", "measles"]].groupby("Year").agg(numpy.sum)
plot = measles_by_year.hvplot(title="Measles In the U.S. by Year", 
                              xlabel="Year", 
                              ylabel="Cases", 
                              width=1000,
                              tools=[hover])
Embed(plot, "measles_by_year")()
#+END_SRC

#+RESULTS:
#+begin_export html
<script src="measles_by_year.js" id="79bcf57c-a4eb-40a9-810f-a73c44db3db0"></script>
#+end_export

You can see from the plot that cases of measles have dropped dramatically over the years, with a particularly sharp drop in the 1960's.
*** Vaccines Enter The Picture
According to the [[https://www.cdc.gov/measles/about/history.html][CDC]], the Edmonston-D vaccine was released in the United States in 1963 and the Edmonston-Enders vaccine (which is still currently in use) was released in 1968.

#+BEGIN_SRC ipython :session pyviz :results output raw :exports both
first = holoviews.VLine(1963).opts(color="black", alpha=0.5)
first_label = holoviews.Text(1963 - 1, 27000, "Vaccine Introduced", halign="right")
current = holoviews.VLine(1968).opts(color="black", alpha=0.5)
current_label = holoviews.Text(1968 + 1, 27000, "Newer Vaccine", halign="left")
highest = holoviews.VLine(int(measles_by_year.idxmax())).opts(color="red")
highest_label = holoviews.Text(int(measles_by_year.idxmax()) + 1, 27000, "Year of the Most Cases", halign="left")
lowest = holoviews.VLine(int(measles_by_year.idxmin())).opts(color="blue", alpha=0.5)
lowest_label = holoviews.Text(int(measles_by_year.idxmin()) - 1, 27000, "Zero Cases", halign="right")

plot_2 = (plot 
          * first * first_label 
          * current * current_label 
          * highest * highest_label 
          * lowest * lowest_label)
Embed(plot_2, "measles_with_landmarks")()
#+END_SRC

#+RESULTS:
#+begin_export html
<script src="measles_with_landmarks.js" id="ba9438e1-8263-49e7-99fb-0de3eb2a3b8c"></script>
#+end_export
*** Measles By State
    This creates a dropdown menu so we can see the states' measles cases separately. It doesn't work in this template so I'm saving it as a separate page.

#+begin_src ipython :session pyviz :results output raw :exports both 
measles_by_state = diseases.groupby(["Year", "State"])["measles"].sum()
states_plot = measles_by_state.hvplot(x="Year", groupby="State", width=800, dynamic=False)
file_name = "measles_by_state.html"
holoviews.save(states_plot, OUTPUT_FOLDER.joinpath(file_name))
print("[[file:{}][Link to plot]]".format(file_name))
#+end_src

#+RESULTS:
[[file:measles_by_state.html][Link to plot]]
*** Oregon Vs Hawaii
    The addition sign is used to make plots next to each other.
#+begin_src ipython :session pyviz :results output raw :exports both 
oregon_plot = states_plot["Oregon"].relabel("Oregon")
hawaii_plot = states_plot["Hawaii"].relabel("Hawaii")
plot = (oregon_plot * first * first_label * current * current_label
        + hawaii_plot * first * first_label * current * current_label)
Embed(plot, "oregon_vs_hawaii")()
#+end_src

#+RESULTS:
#+begin_export html
<script src="oregon_vs_hawaii.js" id="0ac36923-c364-4963-ad01-7cd91ddc6bf7"></script>
#+end_export

I don't know why but the labels don't work. Surprisingly (to me), Hawaii had more cases and with huge swings. Perhaps since it's an island the sailors and other travelers introduced epidemics. Or maybe they weren't as good at keeping records back then.

According to the [[https://en.wikipedia.org/wiki/List_of_U.S._states_and_territories_by_historical_population][Census Count]] Oregon was quite a bit more populous than Hawaii.
*** Four States
    The four states nearest to Hawaii in population are (in descending order):
    - Montana
    - Idaho
    - Hawaii
    - North Dakota
#+begin_src ipython :session pyviz :results output raw :exports both 
states = ["Montana", "Idaho", "Hawaii", "North Dakota"]
plot = (measles_by_state.loc[1930:2005, states].hvplot(
    by="State",
    title="Measles 1930 - 2005",
    width=800) 
        ,* first * first_label 
        ,* current * current_label)
Embed(plot, "four_states_measles")()
#+end_src

#+RESULTS:
#+begin_export html
<script src="four_states_measles.js" id="6342cf49-b434-4915-a802-7350ffc031f6"></script>
#+end_export

* End
