#+BEGIN_COMMENT
.. title: Connected Graphs
.. slug: connected-graphs
.. date: 2020-10-23 19:39:42 UTC-07:00
.. tags: graphs,complexity,networks,erdos
.. category: Complexity
.. link: 
.. description: Generating Connected Graphs.
.. type: text
.. status: 
.. updated: 

#+END_COMMENT
#+OPTIONS: ^:{}
#+TOC: headlines 2

#+PROPERTY: header-args :session ~/.local/share/jupyter/runtime/kernel-a84f1e0f-d2e9-4456-a006-5bb949db3cec.json

#+BEGIN_SRC python :results none :exports none
%load_ext autoreload
%autoreload 2
#+END_SRC
* Beginning
  This is a post about generating completely connected graphs - graphs where every node has a connection to every other node.
** Imports
#+begin_src python :results none
  # pypi
#+end_src
* Middle
** Generating All Node Pairs
   The first part of our puzzle to create connected graphs is a generator function that yields all the pairs from a list of nodes.

#+begin_src python :results none
def all_node_pairs(nodes: list):
    """Generate all unique pairs from nodes

    Args:
      nodes: a list of nodes

    Yields:
     node1, node2: tuple of unique node pairs from nodes
    """
    for index, node in enumerate(nodes):
        for index_2, candidate in enumerate(nodes):
            if index > index_2:
                yield node, candidate
    return
#+end_src

Although it's a "node-pair" generator, it should be noted that any iterable of unique items could be passed through the generator to get unique pairs.
* End
  - The original source for this is {{% doc %}}think-complexity{{% /doc %}}
  - The Master Page for the postss that this is a part of is {{% doc %}}erdos-renyi-graphs{{% /doc %}}
