#+BEGIN_COMMENT
.. title: Opportunity Cost Neglect
.. slug: opportunity-cost-neglect
.. date: 2020-09-26 18:34:45 UTC-07:00
.. tags: bibliography,statistics,psychology,opportunity cost
.. category: Bibliography
.. link: 
.. description: 
.. type: text
.. status: 
.. updated: 

#+END_COMMENT
* Citation
   - Frederick S, Novemsky N, Wang J, Dhar R, Nowlis S. Opportunity cost neglect. Journal of Consumer Research. 2009 Dec 1;36(4):553-61.
* Abstract
** And
To properly consider the opportunity costs of a purchase, consumers must actively generate the alternatives that it would displace. 
** But
The current research suggests that consumers often fail to do so. Even under conditions promoting cognitive effort, various cues to consider opportunity costs reduce purchase rates and increase the choice share of more affordable options. Sensitivity to such cues varies with chronic dispositional differences in spending attitudes. 
** Therefore
We discuss the implications of these results for the marketing strategies of economy and premium brands.
